dbt_learn_repo:
  outputs:
    dev:
      account: TXEFVXV-BT07947
      database: RAW
      password: Rasul!@#$%12345
      role: ACCOUNTADMIN
      schema: JAFFLE_SHOP
      threads: 4
      type: snowflake
      user: KB20260916
      warehouse: TRANSFORMING
  target: dev