dbt_learn_repo:
  outputs:
    dev:
      account: TXEFVXV-BT07947
      database: DEMO_DB
      password: Rasul!@#$%12345
      role: ACCOUNTADMIN
      schema: DBT_RAW
      threads: 1
      type: snowflake
      user: KB20260916
      warehouse: COMPUTE_WH
  target: dev