dbt_learn_repo:
  outputs:
    dev:
      account: *****************
      database: RAW
      password: ******************
      role: ACCOUNTADMIN
      schema: JAFFLE_SHOP
      threads: 4
      type: snowflake
      user: ********************
      warehouse: COMPUTE_WH
  target: dev
